CONTRIBUTING.md

This PR updates references to the branch so that `main` can be used the default branch on this repository.

Refer to main branch

---

.github/workflows/ci.yml
package-lock.json
package.json
syntaxes/smithy.tmLanguage
tests/aggregate-shapes.smithy
tests/control.smithy
tests/metadata.smithy
tests/mixins.smithy
tests/namespace.smithy
tests/service-shapes.smithy
tests/simple-shapes.smithy
tests/traits.smithy
tests/use.smithy

This adds support for some of the new idl syntax for 2.0. Namely it adds
support for:
* optional commas
* inline structure definitions
* the required syntax sugar (e.g. trailing `!`)
* the proposed default syntax sugar (e.g. trailing `= default`)
* mixins via the `with` statement
I do not think it is possible for a TextMate grammar to be able to distinguish
between a key and a value in every case when there are no pair separators,
though I would love to be proven wrong on this.
TM grammars are regex-based, but crucially regexes can never match across
lines. A regex with a newline in the middle, like `foo\nbar` will  NEVER match.
This is to allow the highlighter to be able to re-start at any line if parsing
failed on a previous line. To work around this somewhat, they allow you to
change …

Support Smithy IDL 2.0 syntax

---

package-lock.json
package.json

Upgrades vsce and vscode-nls-dev dependencies to resolve Dependabot alerts.
Resolves https://github.com/awslabs/smithy-vscode/security/dependabot/1
Resolves https://github.com/awslabs/smithy-vscode/security/dependabot/2

Upgrade vsce and vscode-nls-dev

---

package-lock.json
package.json

Upgrades vscode engine and dependencies. Splits out vsce `package` command so that it can be run separately from the `intsll-plugin` command to install to VS Code.

Upgrade engine and dependencies

---

.vscode/launch.json

Adds tests path and disables other extensions, allowing for debugging the extension integration tests via `Run and Debug` pane in VS Code.

Setup launch config for debugging

---

package.json

The Smithy Language Server uses the version `0.0.0-SNAPSHOT`. This updates package.json to set the correctly cased `SNAPSHOT`, fixing the extension being able to launch the Language Server on case-sensitive platforms.

Fix launching LSP on case-sensitive platforms

---

README.md

This PR adds instructions for specifying `smithy-build.json` for use with the Smithy Language Server.

Add smithy-build.json instructions for dependencies

---

test-fixtures/suite1/smithy-build.json
test-fixtures/suite2/smithy-build.json
test-fixtures/suite3/smithy-build.json

This updates the test-fixtures to use the Maven Central repository for fetching the dependency artifacts use by the extension when launching the Smithy Language Server.
Previously these tests would only pass if the dependency artifacts were cached locally.

Fetch test dependencies from Maven Central

---

.vscodeignore
package-lock.json
package.json
tests/runTest.ts
webpack.config.js

This PR adds package bundling to prepare the extension for publication.
This configuration results in a minimal package size with all of the dependencies from `node_modules` (excluding vscode), bundled and minified into extension.js:
```
webpack 5.72.1 compiled successfully in 4164 ms
DONE  Packaged: smithy-vscode.vsix (13 files, 324.21KB)
```
The following files are included in the packaged extension:
```
extension
├── LICENSE.txt
├── NOTICE
├── README.md
├── images
│   └── smithy.png
├── info.plist
├── language-configuration.json
├── out
│   └── src
│       ├── extension.js
│       └── extension.js.map
├── package.json
├── snippets.json
└── syntaxes
└── smithy.tmLanguage
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Bundle extension with webpack

---

README.md
package.json
tests/runTest.ts

This PR updates the extension to use version `0.1.0` of the Smithy Language Server which is not publish to Maven Central.
The extension can be configured to use other versions of the Smithy Language Server, including those published locally to Maven Local, by setting a different version string in the extension's settings:
The integration tests are updated to force installation of the version being tested. This prevents failures if VS Code already has a newer version of the extension already installed.

Use version 0.1.0 of the Smithy Language Server

---

README.md
package-lock.json
package.json

This PR upgrades VSCE and updates the README now that the extension can be installed from the [VS Code Extension Marketplace](https://marketplace.visualstudio.com/items?itemName=smithy.smithy-vscode-extension).

Update VSCE and install instructions

---

package.json
tests/helper.ts
tests/suite1/extension.test.ts
tests/suite2/extension.test.ts

This PR enables the extension tests to be run with CI. It also fixes the test to use the new extension ID: `smithy.smithy-vscode-extension`.

Enable extension tests for CI

---

syntaxes/smithy.tmLanguage.json
tests/grammar/aggregate-shapes.smithy
tests/grammar/enums.smithy
tests/grammar/service-shapes.smithy
tests/grammar/target-elision.smithy

This PR updates the TextMate grammar to support the syntactic sugar that can be used to apply enumValue traits in enum and intEnum shapes and custom default values in structure shapes.

Support enumValue and default value syntactic sugar

---

package.json
test-fixtures/suite1/main.smithy
test-fixtures/suite1/smithy-build.json
test-fixtures/suite2/main.smithy
test-fixtures/suite2/smithy-build.json
test-fixtures/suite3/main.smithy
test-fixtures/suite3/smithy-build.json
tests/suite1/extension.test.ts
tests/suite2/extension.test.ts

Upgrades the extension to use version `0.2.0` of the Smithy Language Server, which has support for Smithy IDL 2.
CI will fail since `0.2.0` of the Smithy Language Server has not yet been published.

Use Language Server 0.2.0 for Smithy IDL 2

---

src/extension.ts

*Issue #, if available:* N/A
*Description of changes:*
By default, whenever the extension sends a message, the focus is switched to VSCode's output window. This change will prevent that from happening so that the user can choose when to check those messages.

feat: never reveal output window when returning

---

README.md
package-lock.json
package.json
src/extension.ts
test-fixtures/suite1/main.smithy
test-fixtures/suite4/.vscode/settings.json
test-fixtures/suite4/smithy/main.smithy
test-fixtures/suite4/smithy/smithy-build.json
tests/runTest.ts
tests/suite4/extension.test.ts
tests/suite4/index.ts

*Issue #, if available:* N/A
*Description of changes:*
Allow users to customize the root path to be used by the Smithy VSCode extension. Otherwise, whenever we have the `smithy-build.json` file not in the workspace root, it fails with the following (as per commit [6e8f997](https://github.com/awslabs/smithy-vscode/pull/54/commits/6e8f9973f3645d15d954d4acdc0bf7e97678da8e)):
<details>
<summary>Dump from .smithy.lsp.log</summary>
[18:14:14] Created a temporary folder for file contents /var/folders/dc/07t_8b2n41lgnz09y651104w0000gn/T/smithy-lsp7987430497366641088
[18:14:14] Recreating project from /smithy-vscode/test-fixtures/suite1
[18:14:14] Imports from config: [/smithy-vscode/test-fixtures/suite1] will be resolved against root /smithy-vscode/test-fixtures/suite1
[18:14:14] Discovered …

feat: add root path configuration

---

.github/workflows/ci.yml

Updates CI to use actions/checkout@v3 and actions/setup-node@v3.
Follows example here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
checkout@v2 and setup-node@v2 use Node 12.x which is EOL.

Upgrade GitHub workflow

---

package.json
src/extension.ts
test-fixtures/suite5/.vscode/settings.json
test-fixtures/suite5/smithy/main.smithy
test-fixtures/suite5/smithy/smithy-build.json
tests/runTest.ts
tests/suite5/extension.test.ts
tests/suite5/index.ts

Registers the Smithy formatter added in https://github.com/awslabs/smithy-language-server/pull/89.
WIP until version `0.2.3` of the Smithy Language Server has been published.

Register formatter

---

src/extension.ts

This PR updates the launch args to explicitly set the Main class from the Smithy Language Server with the `-M` flag.
This ensures the  `software.amazon.smithy.lsp.Main` gets started, rather than relying on Coursier's heuristic to pick the right Main class, which will be needed when upgrading to the next version of the Language Server which includes this change: https://github.com/awslabs/smithy-language-server/pull/113

Explicitly set Main class

---

package.json
smithy-build-schema.json

*Issue #, if available:*
*Description of changes:*
Adds a schema definition file for smithy-build.json. VSCode's builtin JSON language server uses the schema definition to provide completions, hover contents, and validation for smithy-build.json.
The descriptions of properties were taken from the smithy site: https://smithy.io/2.0/guides/building-models/build-config.html#

Add smithy-build.json json schema

---

package-lock.json
package.json
test-fixtures/suite3/.vscode/settings.json
test-fixtures/suite4/.vscode/settings.json
tests/suite4/extension.test.ts

suite3 was failing because it relied on what the server wrote to .smithy.lsp.log, which has to be enabled through the setting 'smithyLsp.logToFile'.
suite4 test workspace had updated smithy trait package dependency versions, but the assertions weren't updated to match. Side note: I think its fine to keep these tests at smithy 1.40, since the extension/server should work fine with whatever smithy version.
Also had to update a dependency so tests could successfully run on Mac.

Fix failing tests, running tests on Mac

---

package-lock.json
package.json
src/extension.ts
test-fixtures/suite1/smithy-build.json
test-fixtures/suite2/smithy-build.json
test-fixtures/suite3/smithy-build.json
test-fixtures/suite4/smithy/smithy-build.json
test-fixtures/suite5/smithy/smithy-build.json
tests/helper.ts
tests/suite1/extension.test.ts
tests/suite2/extension.test.ts
tests/suite3/extension.test.ts
tests/suite4/extension.test.ts
tests/suite5/extension.test.ts

To go along with the changes in the language server 0.4.0: https://github.com/smithy-lang/smithy-language-server/blob/main/CHANGELOG.md#040-2024-07-30, this commit also:
- updates coursier to use java 21 to run the server
- adds config options diagnostics.minimumSeverity, onlyReloadOnSave
- removes config option for logToFile

Upgrade language server version

---

README.md
package.json

Bump to 0.6.0

---

package-lock.json

*Issue #, if available:*
*Description of changes:*
Address known vulnerability on [`path-to-regex`](https://github.com/advisories/GHSA-9wv6-86v2-598j) by running `npm audit fix`.

Ran npm audit fix to update path-to-regexp version

---

syntaxes/smithy.tmLanguage.json

Adds a grammar pattern at the top level for members. While members at the top level aren't valid syntax, having a pattern for them means we can have syntax highlighting in rendered hover content for members.
Before:
After:

Add top-level member pattern
